version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: quickbook_db
    environment:
      POSTGRES_USER: ${ENV_PG_USER}
      POSTGRES_PASSWORD: ${ENV_PG_PASSWORD}
      POSTGRES_DB: ${ENV_PG_DATABASE}
    ports:
      - ${ENV_PG_PORT}:5432
    volumes:
      - quickbook_data:/var/lib/postgresql/data
    networks:
      quickbook-net:
        ipv4_address: ${ENV_PG_HOST}

networks:
  quickbook-net:
    driver: "bridge"
    ipam:
      config:
        - subnet: 178.123.1.0/30

volumes:
  quickbook_data:
