// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventories.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countInventories = `-- name: CountInventories :one
SELECT COUNT(*)
FROM inventories AS i
WHERE i.available_units > 0
  AND (
      $1::text = ''
      OR i.category = $1::text
)
`

func (q *Queries) CountInventories(ctx context.Context, category string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInventories, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listInventories = `-- name: ListInventories :many
SELECT
    i.id,
    i.lessor_id,
    i.name,
    i.category,
    i.rent_per_day,
    i.rent_per_month,
    i.available_units,
    i.health,
    l.username,
    l.email,
    l.phone,
    i.created_at,
    i.updated_at
FROM inventories AS i
LEFT JOIN lessors AS l
    ON l.id = i.lessor_id
WHERE i.available_units > 0
  AND (
      $1::text = ''
      OR i.category = $1::text
  )
ORDER BY i.created_at DESC
LIMIT $3
OFFSET $2
`

type ListInventoriesParams struct {
	Category string
	Offset   int32
	Limit    int32
}

type ListInventoriesRow struct {
	ID             uuid.UUID
	LessorID       uuid.UUID
	Name           string
	Category       string
	RentPerDay     int32
	RentPerMonth   sql.NullInt32
	AvailableUnits sql.NullInt32
	Health         sql.NullFloat64
	Username       sql.NullString
	Email          sql.NullString
	Phone          sql.NullString
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]ListInventoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventories, arg.Category, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoriesRow
	for rows.Next() {
		var i ListInventoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.LessorID,
			&i.Name,
			&i.Category,
			&i.RentPerDay,
			&i.RentPerMonth,
			&i.AvailableUnits,
			&i.Health,
			&i.Username,
			&i.Email,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
