// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Inventory struct {
	ID             uuid.UUID
	LessorID       uuid.UUID
	Name           string
	Category       string
	RentPerDay     int32
	RentPerMonth   sql.NullInt32
	AvailableUnits sql.NullInt32
	Health         sql.NullFloat64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type InventoryPhoto struct {
	ID          uuid.UUID
	InventoryID uuid.UUID
	Photos      []string
}

type Lessor struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Password  string
	City      string
	State     string
	Longitude sql.NullString
	Latitude  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Phone     sql.NullString
}

type PreOwned struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	InventoryID uuid.UUID
}

type Test struct {
	ID       int64
	TestName string
}

type User struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Photo     sql.NullString
	Gender    sql.NullString
	Phone     sql.NullString
	Civil     sql.NullFloat64
	Password  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
