// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test.sql

package db

import (
	"context"
)

const testDB = `-- name: TestDB :one
SELECT
    test_name
FROM test
WHERE id = $1
LIMIT 1
`

func (q *Queries) TestDB(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, testDB, id)
	var test_name string
	err := row.Scan(&test_name)
	return test_name, err
}
